title: ctfs and stuff?
url: https://budorr.github.io
baseurl: ""

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: "press here to go back"
  date_format: "%d-%m-%Y"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
